import * as PIXI from 'https://cdn.jsdelivr.net/npm/pixi.js@8/dist/pixi.mjs';
import { Entity } from './entity.js';
import { input } from '../core/input.js';
import { audio } from '../audio/audio.js';
import { combat } from '../combat/combat.js';
import { ui } from '../ui/ui.js';
import { Inventory } from '../inventory/inventory.js';
import { events } from '../core/events.js';
import { FighterSprite, paletteFromColor } from './fighterSprite.js';
import { ComboSystem } from '../combat/combos.js';
import { WEAPONS } from '../combat/weapons.js';
import { shop } from '../ui/shop.js';
import { SkillSystem } from '../progression/skills.js';

export class Player extends Entity {
 constructor(x,y){super(x,y,40,80);this.stats={str:10,vit:10,agi:10,tech:10};this.level=1;this.xp=0;this.money=50;this.inventory=new Inventory();this.skills=new SkillSystem();this.speed=250;this.depthSpeed=190;this.attackTimer=0;this.attackAnimTimer=0;this.combos=new ComboSystem();this.weapon=null;this.guardTimer=0;this.dashCooldown=0;this.secondWindUsed=false;const palette=paletteFromColor(0x1a3a8f,{skin:0xd4a88a,hair:0x2b1a0f,pants:0x1a1a3e,shoes:0xffffff,accent:0x0a1a4a});this.fighter=new FighterSprite(this.graphics,this.width,this.height,palette);this.fighter.draw();}
 pickUpWeapon(id){const def=WEAPONS[id];if(!def)return;this.weapon={def,uses:0};this.fighter.setWeapon({color:def.color,len:def.len,thick:def.thick});ui.spawnFloatingText(def.name.toUpperCase()+'!',this.x,this.y-40,'#ffdd55');}
 consumeWeaponUse(){if(!this.weapon)return;this.weapon.uses++;if(this.weapon.uses>=this.weapon.def.durability){ui.spawnFloatingText('BROKE!',this.x,this.y-30,'#ff6666');this.weapon=null;this.fighter.setWeapon(null);}}
 update(dt,world){super.update(dt,world);if(this.hp<=0)return;this.inventory.update(dt,this);this.combos.update(dt);if(this.attackTimer>0)this.attackTimer-=dt;if(this.attackAnimTimer>0)this.attackAnimTimer-=dt;if(this.guardTimer>0)this.guardTimer-=dt;if(this.dashCooldown>0)this.dashCooldown-=dt;if(this.hitstun<=0&&this.attackTimer<=0&&!shop.open)this.handleInput(dt,world);else if(shop.open){this.vx=0;this.depthVy=0;}if(this.isGrounded&&this.attackTimer<=0&&input.getAxisX()===0)this.vx*=.8;if(this.isGrounded&&this.attackTimer<=0&&input.getAxisY()===0)this.depthVy*=.8;this.updateAnim(dt);}
 updateAnim(dt){let anim;if(this.hitstun>0)anim='hurt';else if(this.attackAnimTimer>0)anim=this._attackAnim||'punch';else if(!this.isGrounded)anim='jump';else if(Math.abs(this.vx)>20||Math.abs(this.depthVy)>20)anim='walk';else anim='idle';this.fighter.play(anim);this.fighter.update(dt);}
 handleInput(dt,world){let ax=input.getAxisX(),ay=input.getAxisY();const mag=Math.hypot(ax,ay);if(mag>1){ax/=mag;ay/=mag;}const guarding=this.skills.has('guard')&&input.isDown('KeyC')&&mag<.25;if(guarding){this.guardTimer=.12;this.vx=0;this.depthVy=0;this.graphics.tint=0x88bbff;}else{if(this.graphics.tint===0x88bbff)this.graphics.tint=0xffffff;this.vx=ax*this.speed;this.depthVy=ay*this.depthSpeed;}if(this.skills.has('dash')&&input.isJustPressed('KeyC')&&mag>.35&&this.dashCooldown<=0){this.vx=ax*620;this.depthVy=ay*470;this.dashCooldown=.75;this.invincible=Math.max(this.invincible,.18);ui.spawnFloatingText('SHADOW STEP',this.x,this.y-35,'#66ddff');}if(ax!==0||ay!==0){if(Math.abs(ax)>.15)this.dir=ax>0?1:-1;this.state='walk';}else this.state='idle';if(input.isJustPressed('Space')&&this.isGrounded){this.vy=-600;this.isGrounded=false;audio.playJump();}if(input.isJustPressed('KeyZ'))this.attack('light',world);else if(input.isJustPressed('KeyX'))this.attack('heavy',world);}
 attack(type,world){this.vx=0;this.depthVy=0;this.attackTimer=type==='light'?.25:.5;this._attackAnim=type==='heavy'?'punch':((this.combos.count%2===1)?'punch':'kick');this.attackAnimTimer=this.attackTimer;const w=this.weapon?.def;let range=type==='light'?50:70,dmgBonus=0;if(w){range+=w.bonusRange;dmgBonus=w.bonusDamage;}const hx=this.dir===1?this.x+this.width:this.x-range;const hits=combat.checkHits(hx,this.y,range,this.height,this,world);if(!hits.length)return;let launcher=false,slam=false,comboCount=0;if(type==='light'){const info=this.combos.registerLight();comboCount=info.count;launcher=info.isLauncher;}else{const info=this.combos.registerHeavy(hits.some(e=>!e.isGrounded));slam=info.isSlam;}if(launcher&&this.skills.has('uppercut'))launcher='master';const heavyImpact=type==='heavy'||launcher||slam;heavyImpact?audio.playHitHeavy():audio.playHitLight();hits.forEach(enemy=>{let dmg=(type==='light'?this.stats.str:this.stats.str*2.5)+dmgBonus;let kx=type==='heavy'?this.dir*400:this.dir*150,ky=type==='heavy'?-300:-50;if(launcher){dmg*=launcher==='master'?1.8:1.4;kx=this.dir*250;ky=launcher==='master'?-780:-650;}if(slam){dmg*=1.6;kx=this.dir*300;ky=500;}if(type==='heavy'&&this.skills.has('sweep'))enemy.knockdownTimer=1.05;dmg=Math.round(dmg);ui.spawnFloatingText(dmg,enemy.x+enemy.width/2,enemy.y,heavyImpact?'#ffaa00':'#fff');combat.applyImpact(enemy,enemy.x+enemy.width/2,enemy.y+enemy.height*.4-enemy.z,{heavy:heavyImpact,color:launcher?0x66ddff:(slam?0xffcc33:0xffee66)});const dead=enemy.takeDamage(dmg,kx,ky);if(!dead&&heavyImpact)enemy.knockdownTimer=Math.max(enemy.knockdownTimer||0,.65);if(dead){audio.playDeath();events.emit('enemyKilled',enemy.id);this.gainXp(enemy.xp);this.gainMoney(Math.floor(Math.random()*(enemy.gold[1]-enemy.gold[0]))+enemy.gold[0]);if(Math.random()<.28){this.skills.gain(1);ui.spawnFloatingText('+1 JP',this.x,this.y-65,'#66ffff');}if(world.dropWeaponMaybe)world.dropWeaponMaybe(enemy.x+enemy.width/2,enemy.def&&enemy.def.type);world.removeEntity(enemy);}});if(type==='light'&&comboCount>=2)ui.spawnFloatingText(launcher?`COMBO x${comboCount} LAUNCH!`:`COMBO x${comboCount}`,this.x+this.width/2,this.y-55,'#ffee66');else if(slam)ui.spawnFloatingText('SLAM!',this.x+this.width/2,this.y-55,'#ffcc33');if(this.weapon)this.consumeWeaponUse();}
 gainXp(a){this.xp+=a;if(this.xp>=100){this.level++;this.xp-=100;this.maxHp+=25;this.hp=this.maxHp;this.stats.str+=3;this.skills.gain(1);ui.spawnFloatingText('LEVEL UP! +1 JP',this.x,this.y-40,'#00ffff');}}
 gainMoney(a){this.money+=a;audio.playCoin();}
 takeDamage(amt,kx,ky){if(this.guardTimer>0){amt=Math.max(1,Math.round(amt*.28));kx*=.2;ky*=.2;ui.spawnFloatingText('GUARD',this.x,this.y-30,'#88bbff');}let dead=super.takeDamage(amt,kx,ky);if(dead&&this.skills.has('secondWind')&&!this.secondWindUsed){this.secondWindUsed=true;this.hp=Math.ceil(this.maxHp*.25);this.invincible=1.2;dead=false;ui.spawnFloatingText('SECOND WIND!',this.x,this.y-55,'#66ffff');}if(dead)ui.showDialogue('SYSTEM','YOU HAVE FALLEN. REFRESH TO RETRY.');return dead;}
}
