import { combat } from '../combat/combat.js';
import { audio } from '../audio/audio.js';
import { ui } from '../ui/ui.js';

export class AI {
    updateEnemy(enemy,player,dt,world){if(!player||player.hp<=0){this._stop(enemy);return;}const dx=player.x-enemy.x,dy=(player.y+player.height)-(enemy.y+enemy.height),dist=Math.hypot(dx,dy*1.35),depthDist=Math.abs(dy);enemy.dir=dx>=0?1:-1;if(enemy.attackCooldown>0)enemy.attackCooldown-=dt;if(enemy.lungeTimer>0)enemy.lungeTimer-=dt;if(enemy.backoffTimer>0)enemy.backoffTimer-=dt;const type=enemy.def.type,flank=this._flankOffset(enemy,world);if(type==='aggressive')this._updateKnifeWielder(enemy,player,dist,depthDist,flank,world);else if(type==='tank')this._updateBrawler(enemy,player,dist,depthDist,flank,world);else this._updateBasic(enemy,player,dist,depthDist,flank,world);}
    _flankOffset(enemy,world){const a=world.entities.filter(e=>e.def&&e.hp>0);if(a.length<2)return 0;if(enemy._depthFlank===undefined)enemy._depthFlank=(a.indexOf(enemy)%2===0?1:-1)*(42+(a.indexOf(enemy)%3)*18);return enemy._depthFlank;}
    _canAttack(enemy,world){const attackers=world.entities.filter(e=>e!==enemy&&e.def&&e.hp>0&&(e.aiState==='attack'||e.attackAnimTimer>.08));return attackers.length<2;}
    _approach(enemy,player,flankY=0,m=1){let dx=player.x-enemy.x,dy=player.y+player.height+flankY-(enemy.y+enemy.height),len=Math.hypot(dx,dy)||1;dx/=len;dy/=len;enemy.vx=dx*enemy.speed*m;enemy.depthVy=dy*enemy.speed*.78*m;if(Math.abs(dx)>.1)enemy.dir=dx>=0?1:-1;}
    _stop(e){e.vx=0;e.depthVy=0;}
    _circle(enemy,player){enemy.aiState='circle';enemy.vx=-enemy.dir*enemy.speed*.18;enemy.depthVy=(enemy._depthFlank>0?1:-1)*enemy.speed*.38;}
    _updateBasic(e,p,d,dd,f,w){if(d>460){e.aiState='patrol';this._stop(e);}else if(d>72||dd>42){e.aiState='chase';this._approach(e,p,f);}else if(!this._canAttack(e,w)){this._circle(e,p);}else{e.aiState='attack';this._stop(e);if(e.attackCooldown<=0){this.executeAttack(e,w,{range:65});e.attackCooldown=e.def.type==='elite'?1.4:2;}}}
    _updateKnifeWielder(e,p,d,dd,f,w){if(e.backoffTimer>0){e.aiState='backoff';e.vx=-e.dir*e.speed*.9;e.depthVy*=.7;return;}if(d>460){e.aiState='patrol';this._stop(e);}else if(d>92||dd>38){e.aiState='chase';this._approach(e,p,f,1.1);}else if(!this._canAttack(e,w)){this._circle(e,p);}else{e.aiState='attack';this._stop(e);if(e.attackCooldown<=0){e.vx=e.dir*e.speed*2.2;e.lungeTimer=.12;this.executeAttack(e,w,{range:60,quick:true});e.attackCooldown=1.6;e.backoffTimer=.7;}}}
    _updateBrawler(e,p,d,dd,f,w){if(p.attackTimer>0&&!e._sawAttack){e._sawAttack=true;e._playerAttacks=(e._playerAttacks||0)+1;}else if(p.attackTimer<=0)e._sawAttack=false;if(d>460){e.aiState='patrol';this._stop(e);}else if(d>78||dd>42){e.aiState='chase';this._approach(e,p,f,.9);}else if(!this._canAttack(e,w)){this._circle(e,p);}else{this._stop(e);const predictable=(e._playerAttacks||0)>=2;if(predictable&&p.attackTimer>0&&e.blockTimer<=0&&e.attackCooldown<=0){e.aiState='block';e.blockTimer=.5;e.graphics.tint=0x66aaff;clearTimeout(e._blockTintTimer);e._blockTintTimer=setTimeout(()=>{if(e.graphics&&e.hitstun<=0)e.graphics.tint=0xffffff;},300);}else if(e.attackCooldown<=0&&e.blockTimer<=0){e.aiState='attack';this.executeAttack(e,w,{range:72,heavy:true,delay:.35});e.attackCooldown=2.6;e._playerAttacks=0;}}}
    executeAttack(e,w,o={}){const range=o.range||60,heavy=!!o.heavy,delay=o.delay||0;if(e.playAttackAnim)e.playAttackAnim(heavy?.45:.28);const orig=e.graphics.tint;e.graphics.tint=heavy?0xff8800:0xffff00;clearTimeout(e._atkTintTimer);e._atkTintTimer=setTimeout(()=>{if(e.graphics&&e.hitstun<=0)e.graphics.tint=orig;},100+delay*1000);const hit=()=>{if(!w.entities.includes(e)||e.hp<=0||e.knockdownTimer>0)return;const hx=e.dir===1?e.x+e.width:e.x-range,hits=combat.checkHits(hx,e.y,range,e.height,e,w);if(hits.length){heavy?audio.playHitHeavy():audio.playHitLight();hits.forEach(p=>{let dmg=e.def.atk;if(heavy)dmg=Math.round(dmg*1.5);ui.spawnFloatingText(dmg,p.x+p.width/2,p.y-20,'#ff3333');combat.applyImpact(p,p.x+p.width/2,p.y+p.height*.4-p.z,{heavy,color:0xff5555});p.takeDamage(dmg,e.dir*(heavy?320:200),heavy?-220:-150);});}};delay>0?setTimeout(hit,delay*1000):hit();}
}
export const ai=new AI();
